[package]
name = "hacspecs"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hacspec = "0.1"
abstract_integers = "0.1"
num = "0.2"
wrapping_arithmetic = "0.1"

[patch.crates-io]
hacspec = { git = "https://github.com/hacspec/hacspec-rust" }
abstract_integers = { git = "https://github.com/franziskuskiefer/rust-abstract-integers", branch = "dev"}
wrapping_arithmetic = { git = "https://github.com/franziskuskiefer/wrapping-arithmetic" }
